env:
  global:
    - RUST_BACKTRACE=1
    - PATH=$PATH:$HOME/.cargo/bin
os:
  - linux
  - osx
  - windows
language: rust
rust:
  - 1.31.0
sudo: false
cache:
  cargo: true
before_script:
  - if ! cargo prune --version | grep -q "0.1.8"; then
      cargo install cargo-prune --vers="0.1.8" --force;
    fi
  - if ! rustfmt --version | grep -q "1.0.0-stable"; then
      rustup component add rustfmt;
    fi
  - if ! cargo clippy --version | grep -q "0.0.212"; then
      rustup component add clippy;
    fi
script:
  - cargo fmt -- --check &&
    cargo test --verbose --release
  - if [ "${TRAVIS_OS_NAME}" = linux ]; then
      cargo clippy --verbose --release &&
      cargo clippy --verbose --release --profile=test ;
    fi
before_cache:
  - cargo prune
